spring:
  application:
    name: zuul-service

server:
  port: 8303

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka/
  instance:
    hostname: localhost

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      service-id: db-service
    stock-service:
      path: /stock-service/**
      service-id: stock-service